In [1]:
!tree -L data/aclImdb

Too many parameters - data/aclImdb


In [2]:
import sklearn
from sklearn.datasets import load_files
#load_files function is used when a dataset has its labels as subfolders
reviews_train = load_files(".\\aclImdb\\train")
type(reviews_train)
text_train, y_train = reviews_train.data, reviews_train.target
print(f"type of text_train {type(text_train)}")
print(f"length of text_train {len(text_train)}")
print(f"first review in text_train\n {text_train[0]}")

type of text_train <class 'list'>
length of text_train 25000
first review in text_train
 b"Zero Day leads you to think, even re-think why two boys/young men would do what they did - commit mutual suicide via slaughtering their classmates. It captures what must be beyond a bizarre mode of being for two humans who have decided to withdraw from common civility in order to define their own/mutual world via coupled destruction.<br /><br />It is not a perfect movie but given what money/time the filmmaker and actors had - it is a remarkable product. In terms of explaining the motives and actions of the two young suicide/murderers it is better than 'Elephant' - in terms of being a film that gets under our 'rationalistic' skin it is a far, far better film than almost anything you are likely to see. <br /><br />Flawed but honest with a terrible honesty."


In [3]:
text_train = [doc.replace(b"<br />", b"") for doc in text_train]

In [4]:
import numpy as np
print("sample size per class {}".format(np.bincount(y_train)))

sample size per class [12500 12500]


In [5]:
#np.unique(y_train)

In [6]:
reviews_test = load_files(".\\aclImdb\\test")
text_test, y_test = reviews_test.data, reviews_test.target
print("Number of documents in the test data{}".format(len(text_test)))
print("Samples per class{}".format(np.bincount(y_test)))
#print("first review test{}:".format(y_test[0]))
text_test = [doc.replace(b"<br />", b"") for doc in text_test]

Number of documents in the test data25000
Samples per class[12500 12500]


In [7]:
print("first review test \n{}:".format(text_test[0]))
print("first review test \n{}:".format(y_test[0]))

first review test 
b"Don't hate Heather Graham because she's beautiful, hate her because she's fun to watch in this movie. Like the hip clothing and funky surroundings, the actors in this flick work well together. Casey Affleck is hysterical and Heather Graham literally lights up the screen. The minor characters - Goran Visnjic {sigh} and Patricia Velazquez are as TALENTED as they are gorgeous. Congratulations Miramax & Director Lisa Krueger!":
first review test 
1:


## Bag of Words Sample

In [32]:
#isaiah 58:11
favourite_verse =["The LORD will guide you continually",
                  "giving you water when you are dry and restoring your strength",
                  "You will be like a well-watered garden",
                  "like an ever-flowing spring."]

In [33]:
#we cound all the words and assign them a position
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
vect.fit(favourite_verse)

CountVectorizer()

In [35]:
#vocabulary_ is a coefficient of feature
print("Vocabulary Size {}".format(len(vect.vocabulary_)))
print("Vocabulary content \n{}".format(vect.vocabulary_))

Vocabulary Size 24
Vocabulary content 
{'the': 16, 'lord': 12, 'will': 21, 'guide': 10, 'you': 22, 'continually': 4, 'giving': 9, 'water': 17, 'when': 20, 'are': 2, 'dry': 5, 'and': 1, 'restoring': 13, 'your': 23, 'strength': 15, 'be': 3, 'like': 11, 'well': 19, 'watered': 18, 'garden': 8, 'an': 0, 'ever': 6, 'flowing': 7, 'spring': 14}


In [36]:
#creating bag of words
bag_of_words = vect.transform(favourite_verse)
print("bag_of_words {}".format(repr(favourite_verse)))

bag_of_words ['The LORD will guide you continually', 'giving you water when you are dry and restoring your strength', 'You will be like a well-watered garden', 'like an ever-flowing spring.']


In [37]:
#convertuing from sparse to array we use the to array function from numpy
import numpy as np
print("Dense representation of the bag of words: \n{}".format(bag_of_words.toarray()))

Dense representation of the bag of words: 
[[0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 0]
 [0 1 1 0 0 1 0 0 0 1 0 0 0 1 0 1 0 1 0 0 1 0 2 1]
 [0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 1 0 1 1 0]
 [1 0 0 0 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0]]
